-- Batch 1/5: correct primary passages that had no verse range.
-- 12 of these had the wrong book or chapter entirely (the first-transcript-ref
-- heuristic picked up a passing mention). Mirrors tools/fix_passage.py exactly:
-- passage_ref (rebuilds item_fts via trigger) + the is_primary/source='primary' row.
-- Transcript-mined refs (source='transcript') are untouched. collection_id is NOT
-- touched, so the 2 Samuel sermons stay in the psalm-51 series.
UPDATE items SET passage_ref='Psalms 96:1-13' WHERE id=1;
DELETE FROM scripture_refs WHERE item_id=1 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (1, 'Psalms', 96, 1, 13, 1, 'Psalms 96:1-13', 'primary');
UPDATE items SET passage_ref='1 Peter 1:1' WHERE id=2;
DELETE FROM scripture_refs WHERE item_id=2 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (2, '1 Peter', 1, 1, NULL, 1, '1 Peter 1:1', 'primary');
UPDATE items SET passage_ref='1 Peter 1:1' WHERE id=3;
DELETE FROM scripture_refs WHERE item_id=3 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (3, '1 Peter', 1, 1, NULL, 1, '1 Peter 1:1', 'primary');
UPDATE items SET passage_ref='1 Peter 1:1-2' WHERE id=4;
DELETE FROM scripture_refs WHERE item_id=4 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (4, '1 Peter', 1, 1, 2, 1, '1 Peter 1:1-2', 'primary');
UPDATE items SET passage_ref='1 Peter 1:3-6' WHERE id=6;
DELETE FROM scripture_refs WHERE item_id=6 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (6, '1 Peter', 1, 3, 6, 1, '1 Peter 1:3-6', 'primary');
UPDATE items SET passage_ref='1 Peter 1:9-12' WHERE id=8;
DELETE FROM scripture_refs WHERE item_id=8 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (8, '1 Peter', 1, 9, 12, 1, '1 Peter 1:9-12', 'primary');
UPDATE items SET passage_ref='1 Peter 1:15-21' WHERE id=9;
DELETE FROM scripture_refs WHERE item_id=9 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (9, '1 Peter', 1, 15, 21, 1, '1 Peter 1:15-21', 'primary');
UPDATE items SET passage_ref='LBCF 8.5' WHERE id=10;
DELETE FROM scripture_refs WHERE item_id=10 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (10, 'LBCF', 8, 5, NULL, 1, 'LBCF 8.5', 'primary');
UPDATE items SET passage_ref='1 Peter 1:22-25' WHERE id=11;
DELETE FROM scripture_refs WHERE item_id=11 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (11, '1 Peter', 1, 22, 25, 1, '1 Peter 1:22-25', 'primary');
UPDATE items SET passage_ref='1 Peter 2:1-3' WHERE id=12;
DELETE FROM scripture_refs WHERE item_id=12 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (12, '1 Peter', 2, 1, 3, 1, '1 Peter 2:1-3', 'primary');
UPDATE items SET passage_ref='1 Peter 2:4-10' WHERE id=13;
DELETE FROM scripture_refs WHERE item_id=13 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (13, '1 Peter', 2, 4, 10, 1, '1 Peter 2:4-10', 'primary');
UPDATE items SET passage_ref='Psalms 84:1-12' WHERE id=15;
DELETE FROM scripture_refs WHERE item_id=15 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (15, 'Psalms', 84, 1, 12, 1, 'Psalms 84:1-12', 'primary');
UPDATE items SET passage_ref='1 Peter 2:11-16' WHERE id=16;
DELETE FROM scripture_refs WHERE item_id=16 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (16, '1 Peter', 2, 11, 16, 1, '1 Peter 2:11-16', 'primary');
UPDATE items SET passage_ref='1 Peter 2:18-25' WHERE id=18;
DELETE FROM scripture_refs WHERE item_id=18 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (18, '1 Peter', 2, 18, 25, 1, '1 Peter 2:18-25', 'primary');
UPDATE items SET passage_ref='1 Peter 3:1-6' WHERE id=20;
DELETE FROM scripture_refs WHERE item_id=20 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (20, '1 Peter', 3, 1, 6, 1, '1 Peter 3:1-6', 'primary');
UPDATE items SET passage_ref='Philippians 2:5-11' WHERE id=21;
DELETE FROM scripture_refs WHERE item_id=21 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (21, 'Philippians', 2, 5, 11, 1, 'Philippians 2:5-11', 'primary');
UPDATE items SET passage_ref='1 Peter 3:8' WHERE id=25;
DELETE FROM scripture_refs WHERE item_id=25 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (25, '1 Peter', 3, 8, NULL, 1, '1 Peter 3:8', 'primary');
UPDATE items SET passage_ref='Psalms 98:1-9' WHERE id=26;
DELETE FROM scripture_refs WHERE item_id=26 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (26, 'Psalms', 98, 1, 9, 1, 'Psalms 98:1-9', 'primary');
UPDATE items SET passage_ref='1 Peter 3:8-13' WHERE id=28;
DELETE FROM scripture_refs WHERE item_id=28 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (28, '1 Peter', 3, 8, 13, 1, '1 Peter 3:8-13', 'primary');
UPDATE items SET passage_ref='1 Peter 3:13-16' WHERE id=29;
DELETE FROM scripture_refs WHERE item_id=29 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (29, '1 Peter', 3, 13, 16, 1, '1 Peter 3:13-16', 'primary');
UPDATE items SET passage_ref='1 Peter 3:18-20' WHERE id=31;
DELETE FROM scripture_refs WHERE item_id=31 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (31, '1 Peter', 3, 18, 20, 1, '1 Peter 3:18-20', 'primary');
UPDATE items SET passage_ref='1 Peter 4:1-6' WHERE id=32;
DELETE FROM scripture_refs WHERE item_id=32 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (32, '1 Peter', 4, 1, 6, 1, '1 Peter 4:1-6', 'primary');
UPDATE items SET passage_ref='1 Peter 4:7' WHERE id=33;
DELETE FROM scripture_refs WHERE item_id=33 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (33, '1 Peter', 4, 7, NULL, 1, '1 Peter 4:7', 'primary');
UPDATE items SET passage_ref='1 Peter 4:7-9' WHERE id=34;
DELETE FROM scripture_refs WHERE item_id=34 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (34, '1 Peter', 4, 7, 9, 1, '1 Peter 4:7-9', 'primary');
UPDATE items SET passage_ref='1 Peter 4:10-11' WHERE id=35;
DELETE FROM scripture_refs WHERE item_id=35 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (35, '1 Peter', 4, 10, 11, 1, '1 Peter 4:10-11', 'primary');
UPDATE items SET passage_ref='1 Peter 4:12-19' WHERE id=37;
DELETE FROM scripture_refs WHERE item_id=37 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (37, '1 Peter', 4, 12, 19, 1, '1 Peter 4:12-19', 'primary');
UPDATE items SET passage_ref='1 Peter 5:1-4' WHERE id=38;
DELETE FROM scripture_refs WHERE item_id=38 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (38, '1 Peter', 5, 1, 4, 1, '1 Peter 5:1-4', 'primary');
UPDATE items SET passage_ref='1 Peter 5:10-14' WHERE id=40;
DELETE FROM scripture_refs WHERE item_id=40 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (40, '1 Peter', 5, 10, 14, 1, '1 Peter 5:10-14', 'primary');
UPDATE items SET passage_ref='John 13:1-11' WHERE id=41;
DELETE FROM scripture_refs WHERE item_id=41 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (41, 'John', 13, 1, 11, 1, 'John 13:1-11', 'primary');
UPDATE items SET passage_ref='2 Samuel 11:1-5' WHERE id=43;
DELETE FROM scripture_refs WHERE item_id=43 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (43, '2 Samuel', 11, 1, 5, 1, '2 Samuel 11:1-5', 'primary');
UPDATE items SET passage_ref='2 Samuel 11:6-27' WHERE id=45;
DELETE FROM scripture_refs WHERE item_id=45 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (45, '2 Samuel', 11, 6, 27, 1, '2 Samuel 11:6-27', 'primary');
UPDATE items SET passage_ref='2 Samuel 12:1-15' WHERE id=46;
DELETE FROM scripture_refs WHERE item_id=46 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (46, '2 Samuel', 12, 1, 15, 1, '2 Samuel 12:1-15', 'primary');
UPDATE items SET passage_ref='2 Samuel 12:15-25' WHERE id=47;
DELETE FROM scripture_refs WHERE item_id=47 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (47, '2 Samuel', 12, 15, 25, 1, '2 Samuel 12:15-25', 'primary');
UPDATE items SET passage_ref='Psalms 51:4-7' WHERE id=48;
DELETE FROM scripture_refs WHERE item_id=48 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (48, 'Psalms', 51, 4, 7, 1, 'Psalms 51:4-7', 'primary');
UPDATE items SET passage_ref='Psalms 51:8-12' WHERE id=49;
DELETE FROM scripture_refs WHERE item_id=49 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (49, 'Psalms', 51, 8, 12, 1, 'Psalms 51:8-12', 'primary');
