-- Batch 2/5: correct primary passages that had no verse range.
-- Mostly the Jonah series, which the first-transcript-ref heuristic scattered
-- across Psalms 18/31/119, Romans 11, Hebrews 11, Jeremiah 15, Genesis 4 and
-- Ephesians 4 -- he quotes those while preaching Jonah. Mirrors fix_passage.py.
-- SKIPPED id=58: text never named in window (topical talk on sexuality)
-- SKIPPED id=99: text not read in window; title implies John 3 but unconfirmed
UPDATE items SET passage_ref='Psalms 51:9-16' WHERE id=50;
DELETE FROM scripture_refs WHERE item_id=50 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (50, 'Psalms', 51, 9, 16, 1, 'Psalms 51:9-16', 'primary');
UPDATE items SET passage_ref='Acts 20:28' WHERE id=51;
DELETE FROM scripture_refs WHERE item_id=51 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (51, 'Acts', 20, 28, NULL, 1, 'Acts 20:28', 'primary');
UPDATE items SET passage_ref='Psalms 51:8-15' WHERE id=52;
DELETE FROM scripture_refs WHERE item_id=52 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (52, 'Psalms', 51, 8, 15, 1, 'Psalms 51:8-15', 'primary');
UPDATE items SET passage_ref='Psalms 51:16-19' WHERE id=53;
DELETE FROM scripture_refs WHERE item_id=53 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (53, 'Psalms', 51, 16, 19, 1, 'Psalms 51:16-19', 'primary');
UPDATE items SET passage_ref='Matthew 18:15-20' WHERE id=55;
DELETE FROM scripture_refs WHERE item_id=55 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (55, 'Matthew', 18, 15, 20, 1, 'Matthew 18:15-20', 'primary');
UPDATE items SET passage_ref='LBCF 30.6' WHERE id=56;
DELETE FROM scripture_refs WHERE item_id=56 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (56, 'LBCF', 30, 6, NULL, 1, 'LBCF 30.6', 'primary');
UPDATE items SET passage_ref='1 Corinthians 5:1-13' WHERE id=57;
DELETE FROM scripture_refs WHERE item_id=57 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (57, '1 Corinthians', 5, 1, 13, 1, '1 Corinthians 5:1-13', 'primary');
UPDATE items SET passage_ref='James 5:19-20' WHERE id=59;
DELETE FROM scripture_refs WHERE item_id=59 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (59, 'James', 5, 19, 20, 1, 'James 5:19-20', 'primary');
UPDATE items SET passage_ref='Hebrews 12:1-2' WHERE id=70;
DELETE FROM scripture_refs WHERE item_id=70 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (70, 'Hebrews', 12, 1, 2, 1, 'Hebrews 12:1-2', 'primary');
UPDATE items SET passage_ref='Matthew 5:6' WHERE id=72;
DELETE FROM scripture_refs WHERE item_id=72 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (72, 'Matthew', 5, 6, NULL, 1, 'Matthew 5:6', 'primary');
UPDATE items SET passage_ref='Hebrews 7:25' WHERE id=80;
DELETE FROM scripture_refs WHERE item_id=80 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (80, 'Hebrews', 7, 25, NULL, 1, 'Hebrews 7:25', 'primary');
UPDATE items SET passage_ref='Galatians 6:7-10' WHERE id=88;
DELETE FROM scripture_refs WHERE item_id=88 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (88, 'Galatians', 6, 7, 10, 1, 'Galatians 6:7-10', 'primary');
UPDATE items SET passage_ref='2 Corinthians 6:14-18' WHERE id=98;
DELETE FROM scripture_refs WHERE item_id=98 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (98, '2 Corinthians', 6, 14, 18, 1, '2 Corinthians 6:14-18', 'primary');
UPDATE items SET passage_ref='Isaiah 53:1-12' WHERE id=103;
DELETE FROM scripture_refs WHERE item_id=103 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (103, 'Isaiah', 53, 1, 12, 1, 'Isaiah 53:1-12', 'primary');
UPDATE items SET passage_ref='Proverbs 22:6' WHERE id=110;
DELETE FROM scripture_refs WHERE item_id=110 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (110, 'Proverbs', 22, 6, NULL, 1, 'Proverbs 22:6', 'primary');
UPDATE items SET passage_ref='1 Timothy 3:1-7' WHERE id=112;
DELETE FROM scripture_refs WHERE item_id=112 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (112, '1 Timothy', 3, 1, 7, 1, '1 Timothy 3:1-7', 'primary');
UPDATE items SET passage_ref='Jonah 1:1-17' WHERE id=113;
DELETE FROM scripture_refs WHERE item_id=113 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (113, 'Jonah', 1, 1, 17, 1, 'Jonah 1:1-17', 'primary');
UPDATE items SET passage_ref='Psalms 139:1-24' WHERE id=114;
DELETE FROM scripture_refs WHERE item_id=114 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (114, 'Psalms', 139, 1, 24, 1, 'Psalms 139:1-24', 'primary');
UPDATE items SET passage_ref='Jonah 1:1-3' WHERE id=115;
DELETE FROM scripture_refs WHERE item_id=115 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (115, 'Jonah', 1, 1, 3, 1, 'Jonah 1:1-3', 'primary');
UPDATE items SET passage_ref='Jonah 1:1' WHERE id=116;
DELETE FROM scripture_refs WHERE item_id=116 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (116, 'Jonah', 1, 1, NULL, 1, 'Jonah 1:1', 'primary');
UPDATE items SET passage_ref='Jonah 1:1-7' WHERE id=117;
DELETE FROM scripture_refs WHERE item_id=117 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (117, 'Jonah', 1, 1, 7, 1, 'Jonah 1:1-7', 'primary');
UPDATE items SET passage_ref='Jonah 1:1-10' WHERE id=118;
DELETE FROM scripture_refs WHERE item_id=118 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (118, 'Jonah', 1, 1, 10, 1, 'Jonah 1:1-10', 'primary');
UPDATE items SET passage_ref='Matthew 14:22-33' WHERE id=119;
DELETE FROM scripture_refs WHERE item_id=119 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (119, 'Matthew', 14, 22, 33, 1, 'Matthew 14:22-33', 'primary');
UPDATE items SET passage_ref='Romans 13:11-14' WHERE id=120;
DELETE FROM scripture_refs WHERE item_id=120 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (120, 'Romans', 13, 11, 14, 1, 'Romans 13:11-14', 'primary');
UPDATE items SET passage_ref='Jonah 1:4-16' WHERE id=121;
DELETE FROM scripture_refs WHERE item_id=121 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (121, 'Jonah', 1, 4, 16, 1, 'Jonah 1:4-16', 'primary');
UPDATE items SET passage_ref='Jonah 2:1-7' WHERE id=122;
DELETE FROM scripture_refs WHERE item_id=122 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (122, 'Jonah', 2, 1, 7, 1, 'Jonah 2:1-7', 'primary');
UPDATE items SET passage_ref='Jonah 2:7-9' WHERE id=123;
DELETE FROM scripture_refs WHERE item_id=123 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (123, 'Jonah', 2, 7, 9, 1, 'Jonah 2:7-9', 'primary');
UPDATE items SET passage_ref='Jonah 2:8-9' WHERE id=124;
DELETE FROM scripture_refs WHERE item_id=124 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (124, 'Jonah', 2, 8, 9, 1, 'Jonah 2:8-9', 'primary');
UPDATE items SET passage_ref='Jonah 2:10' WHERE id=125;
DELETE FROM scripture_refs WHERE item_id=125 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (125, 'Jonah', 2, 10, NULL, 1, 'Jonah 2:10', 'primary');
UPDATE items SET passage_ref='Jonah 3:1-3' WHERE id=126;
DELETE FROM scripture_refs WHERE item_id=126 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (126, 'Jonah', 3, 1, 3, 1, 'Jonah 3:1-3', 'primary');
UPDATE items SET passage_ref='Psalms 89:19-33' WHERE id=127;
DELETE FROM scripture_refs WHERE item_id=127 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (127, 'Psalms', 89, 19, 33, 1, 'Psalms 89:19-33', 'primary');
UPDATE items SET passage_ref='Jonah 3:1-10' WHERE id=128;
DELETE FROM scripture_refs WHERE item_id=128 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (128, 'Jonah', 3, 1, 10, 1, 'Jonah 3:1-10', 'primary');
UPDATE items SET passage_ref='Jonah 4:1-11' WHERE id=129;
DELETE FROM scripture_refs WHERE item_id=129 AND is_primary=1;
INSERT INTO scripture_refs (item_id, book, chapter, verse_start, verse_end, is_primary, ref_text, source) VALUES (129, 'Jonah', 4, 1, 11, 1, 'Jonah 4:1-11', 'primary');
